---
- name: install run and enable {{ package }}
  hosts: localhost
  tasks:
  - name: install {{ package }}
    package:
      name: "{{ package }}"
      state: latest
  - name: run and enable {{ package }}
    service:
      name: "{{ package }}"
      state: started
      enabled: yes
