---
- name: install run and enable {{ something }}
  hosts: localhost
  tasks:
  - name: install {{ something }}
    package:
      name: "{{ something }}"
      state: latest
  - name: run and enable {{ something }}
    service:
      name: "{{ something }}"
      state: started
      enabled: yes
